package com.example.four_pic.repository

import com.example.four_pic.R
import com.example.four_pic.models.QuestionData
//import com.example.four_pic.room.AppDatabase

class Repositoru {
    var questionsList_3and4 = ArrayList<QuestionData>()
    var questionsList_5and6 = ArrayList<QuestionData>()
    var questionsList_7and8 = ArrayList<QuestionData>()
//    private val trainerDao = AppDatabase.database?.inputData()!!

//    fun getAllResults() = trainerDao.getAllTrainer()

    fun getAllQuestions(){
        // add questions 3 4 harfli javobliside karochi karochi
        questionsList_3and4.add(QuestionData(R.drawable.img_3_1,"bat", "tsbgaawffa"))
        questionsList_3and4.add(QuestionData(R.drawable.img_3_2,"can", "dnqdracfaa"))
        questionsList_3and4.add(QuestionData(R.drawable.img_3_3,"fan", "flapfwasnf"))
        questionsList_3and4.add(QuestionData(R.drawable.img_3_4,"hot", "osadtzfqha"))
        questionsList_3and4.add(QuestionData(R.drawable.img_3_5,"bow", "bdffadwgfo"))
        questionsList_3and4.add(QuestionData(R.drawable.img_3_6,"row", "walolfffra"))
        questionsList_3and4.add(QuestionData(R.drawable.img_3_7,"tip","aftfsjphid"))
        questionsList_3and4.add(QuestionData(R.drawable.img_3_8,"oil","olfagahfdi"))
        questionsList_3and4.add(QuestionData(R.drawable.img_3_9,"old","dlofwagjha"))
        questionsList_3and4.add(QuestionData(R.drawable.img_3_10,"dry","jfkyadrfds"))
        questionsList_3and4.add(QuestionData(R.drawable.img_3_11,"tie","gaisthejfg"))
        questionsList_3and4.add(QuestionData(R.drawable.img_3_12,"red", "hadbaehkwr"))
        questionsList_3and4.add(QuestionData(R.drawable.img_3_13,"new", "gtswbnshae"))
        questionsList_3and4.add(QuestionData(R.drawable.img_3_14,"raw", "tadeartbaw"))
        questionsList_3and4.add(QuestionData(R.drawable.img_3_15,"net", "tamfljenba"))
        questionsList_3and4.add(QuestionData(R.drawable.img_4_1,"ball", "tlfghtlbva"))
        questionsList_3and4.add(QuestionData(R.drawable.img_4_2,"fish", "tsifbahfad"))
        questionsList_3and4.add(QuestionData(R.drawable.img_4_3,"pair", "tpdaiarfba")    )
        questionsList_3and4.add(QuestionData(R.drawable.img_4_4,"jump", "jahafumagp"))
        questionsList_3and4.add(QuestionData(R.drawable.img_4_5,"date", "ddazgthdeh"))
        questionsList_3and4.add(QuestionData(R.drawable.img_4_6,"full", "fadudaglhl"))
        questionsList_3and4.add(QuestionData(R.drawable.img_4_7,"blue", "abdlgugfea"))
        questionsList_3and4.add(QuestionData(R.drawable.img_4_8,"bill", "baifaldlad"))
        questionsList_3and4.add(QuestionData(R.drawable.img_4_9,"sign", "asfiffdagn"))
        questionsList_3and4.add(QuestionData(R.drawable.img_4_10,"wave","dwffagadve"))
        questionsList_3and4.add(QuestionData(R.drawable.img_4_11,"luck","laffucgaka"))
        questionsList_3and4.add(QuestionData(R.drawable.img_4_12,"cold","cdfogalgad"))
        questionsList_3and4.add(QuestionData(R.drawable.img_4_13,"game","ggaxagmdea"))
        questionsList_3and4.add(QuestionData(R.drawable.img_4_14,"code","cgaoafdade"))
        questionsList_3and4.add(QuestionData(R.drawable.img_4_15,"hard","hfagahrhad"))

    // add questions 3 4 harfli javobliside karochi karochi
        questionsList_5and6.add(QuestionData(R.drawable.img_5_1,"dirty","ddisarfyjt"))
        questionsList_5and6.add(QuestionData(R.drawable.img_5_2,"water","wdgaataegr"))
        questionsList_5and6.add(QuestionData(R.drawable.img_5_3,"cross","afcgrhosas"))
        questionsList_5and6.add(QuestionData(R.drawable.img_5_4,"alarm","azlmaframf"))
        questionsList_5and6.add(QuestionData(R.drawable.img_5_5,"pound","pzvbouandd"))
        questionsList_5and6.add(QuestionData(R.drawable.img_5_6,"train","tbrfaainer"))
        questionsList_5and6.add(QuestionData(R.drawable.img_5_7,"sweet","asgwgaeeft"))
        questionsList_5and6.add(QuestionData(R.drawable.img_5_8,"drink","dzrcvihngk"))
        questionsList_5and6.add(QuestionData(R.drawable.img_5_9,"round","rfoabunnxd"))
        questionsList_5and6.add(QuestionData(R.drawable.img_5_10,"white","awdhagijte"))
        questionsList_5and6.add(QuestionData(R.drawable.img_5_11,"crane","cdrhanahea"))
        questionsList_5and6.add(QuestionData(R.drawable.img_5_12,"black","dbgalhachk"))
        questionsList_5and6.add(QuestionData(R.drawable.img_5_13,"trunk","tdrgaunhak"))
        questionsList_5and6.add(QuestionData(R.drawable.img_5_14,"quiet","qafauihget"))
        questionsList_5and6.add(QuestionData(R.drawable.img_5_15,"match","maagtgacah"))
        questionsList_5and6.add(QuestionData(R.drawable.img_5_16,"sports","slpzorntas"))
        questionsList_5and6.add(QuestionData(R.drawable.img_5_17,"hiphop","hgipahochp"))
        questionsList_5and6.add(QuestionData(R.drawable.img_5_18,"square","gsqupaihre"))
        questionsList_5and6.add(QuestionData(R.drawable.img_5_19,"yellow","byevlclzow"))
        questionsList_5and6.add(QuestionData(R.drawable.img_5_20,"strong","sttrqbongg"))
        questionsList_5and6.add(QuestionData(R.drawable.img_5_21,"record","rfeccocrvd"))
        questionsList_5and6.add(QuestionData(R.drawable.img_5_22,"vacuum","fvcabcuunm"))
        questionsList_5and6.add(QuestionData(R.drawable.img_5_23,"barrel","bnarhrkjel"))
        questionsList_5and6.add(QuestionData(R.drawable.img_5_24,"minute","mlijnkutje"))
        questionsList_5and6.add(QuestionData(R.drawable.img_5_25,"letter","lgeftatehr"))
        questionsList_5and6.add(QuestionData(R.drawable.img_5_26,"narrow","nadrdrdowg"))
        questionsList_5and6.add(QuestionData(R.drawable.img_5_27,"spiral","szpdixragl"))
        questionsList_5and6.add(QuestionData(R.drawable.img_5_28,"change","chviannlge"))
        questionsList_5and6.add(QuestionData(R.drawable.img_5_29,"summer","ysuimmmekr"))
        questionsList_5and6.add(QuestionData(R.drawable.img_5_30,"plenty","plhelhntfy"))

        // 7 va 8 tali harflarga qo'shilvotti
        questionsList_7and8.add(QuestionData(R.drawable.img_7_1,"morning", "modrnaingg"))
        questionsList_7and8.add(QuestionData(R.drawable.img_7_2,"present", "prdesgaent"))
        questionsList_7and8.add(QuestionData(R.drawable.img_7_3,"gesture", "aggestaure"))
        questionsList_7and8.add(QuestionData(R.drawable.img_7_4,"address", "adhdrfesas"))
        questionsList_7and8.add(QuestionData(R.drawable.img_7_5,"collect", "cxolalehct"))
        questionsList_7and8.add(QuestionData(R.drawable.img_7_6,"seasons", "lseahsofns"))
        questionsList_7and8.add(QuestionData(R.drawable.img_7_7,"clothes", "clotffheks"))
        questionsList_7and8.add(QuestionData(R.drawable.img_7_8,"costume", "cosbtbukme"))
        questionsList_7and8.add(QuestionData(R.drawable.img_7_9,"balance", "bzalandfce"))
        questionsList_7and8.add(QuestionData(R.drawable.img_7_10,"weather", "wevacthher"))
        questionsList_7and8.add(QuestionData(R.drawable.img_7_11,"germany", "gedrmagnyh"))
        questionsList_7and8.add(QuestionData(R.drawable.img_7_12,"produce", "paroddugce"))
        questionsList_7and8.add(QuestionData(R.drawable.img_7_13,"burnout", "bubrnogzut"))
        questionsList_7and8.add(QuestionData(R.drawable.img_7_14,"capture", "chapbturce"))
        questionsList_7and8.add(QuestionData(R.drawable.img_7_15,"perform", "pnerjfoarm"))
        questionsList_7and8.add(QuestionData(R.drawable.img_8_1,"children", "nrehdilcjn"))
        questionsList_7and8.add(QuestionData(R.drawable.img_8_2,"overkill", "lkirlvmejo"))
        questionsList_7and8.add(QuestionData(R.drawable.img_8_3,"receiver", "ceierervni"))
        questionsList_7and8.add(QuestionData(R.drawable.img_8_4,"assemble", "ssnmlebafje"))
        questionsList_7and8.add(QuestionData(R.drawable.img_8_5,"conflict", "NTIDCFLOCF"))
        questionsList_7and8.add(QuestionData(R.drawable.img_8_6,"negative", "tafiedgevn"))
        questionsList_7and8.add(QuestionData(R.drawable.img_8_7,"indicate", "ceditenida"))
        questionsList_7and8.add(QuestionData(R.drawable.img_8_8,"dominate", "omtnejahid"))
        questionsList_7and8.add(QuestionData(R.drawable.img_8_9,"premiere", "eemrerpfai"))
        questionsList_7and8.add(QuestionData(R.drawable.img_8_10,"scavenge", "bcvgseenea"))
        questionsList_7and8.add(QuestionData(R.drawable.img_8_11,"converse", "ereccvozns"))
        questionsList_7and8.add(QuestionData(R.drawable.img_8_12,"meditate", "tidaeztmde"))
        questionsList_7and8.add(QuestionData(R.drawable.img_8_13,"vacation", "anivoxctaw"))
        questionsList_7and8.add(QuestionData(R.drawable.img_8_14,"gambling", "gxgnamiblz"))
        questionsList_7and8.add(QuestionData(R.drawable.img_8_15,"geometry", "mvtroeemgy"))
    }
}